# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param n the number of between-sample random numbers
#' @param a the first parameter of Beta distribution
#' @param b the second parameter of Beta distribution
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' set.seed(1230)
#' NumericMatrix gibbsC(1000,1000,1,1)
#' }
#' @export
gibbsC <- function(N, n, a, b) {
    .Call('_StatComp21059_gibbsC', PACKAGE = 'StatComp21059', N, n, a, b)
}

